#!/usr/bin/env node
/**
 * Regenerate every artifact derived from the published `/v1` OpenAPI contract.
 *
 *     npm run codegen
 *
 * Writes, all committed so a contract change lands as a reviewable diff:
 *
 *   tests/contract/openapi/platform-v1.json          the contract snapshot
 *   sdks/typescript/src/generated/types.ts           request/response types
 *   sdks/typescript/src/generated/operations.ts      operationId -> method + path
 *   sdks/python/src/octogen_ai_sdk/generated/models.py       request/response models
 *   sdks/python/src/octogen_ai_sdk/generated/operations.py   operationId -> method + path
 *
 * Per D4 of the CLI design this is the *hybrid* half: types are generated, the
 * method layer is hand-written, and `tests/contract` is what keeps the two
 * honest. Do not hand-edit anything under a `generated/` directory.
 *
 * The two generators are pinned and run one-shot rather than added as
 * dependencies: `openapi-typescript` peers on TypeScript 5 while this repo is
 * on 6, and neither tool is needed except when the contract moves.
 */
import { execFileSync } from "node:child_process";
import { mkdirSync, writeFileSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const CONTRACT_URL =
  process.env["OCTOGEN_OPENAPI_URL"] ??
  "https://cdn.octogen.ai/openapi/platform/v1/openapi.json";

const OPENAPI_TYPESCRIPT = "openapi-typescript@7.13.0";
const DATAMODEL_CODE_GENERATOR = "datamodel-code-generator==0.74.0";

const root = path.dirname(path.dirname(fileURLToPath(import.meta.url)));
const contractPath = path.join(root, "tests/contract/openapi/platform-v1.json");
const tsGenerated = path.join(root, "sdks/typescript/src/generated");
const pyGenerated = path.join(root, "sdks/python/src/octogen_ai_sdk/generated");

const BANNER = [
  "// Generated by `npm run codegen` from the published Octogen Platform",
  "// Catalog API v1 contract. Do not edit by hand.",
].join("\n");

const PY_BANNER = [
  '"""Generated by `npm run codegen` from the published Octogen Platform',
  "Catalog API v1 contract. Do not edit by hand.",
  '"""',
].join("\n");

function run(command, args, options = {}) {
  return execFileSync(command, args, {
    cwd: root,
    encoding: "utf8",
    stdio: ["ignore", "pipe", "inherit"],
    ...options,
  });
}

async function fetchContract() {
  console.log(`fetching ${CONTRACT_URL}`);
  const response = await fetch(CONTRACT_URL);
  if (!response.ok) {
    throw new Error(`${CONTRACT_URL} returned ${String(response.status)}`);
  }
  return await response.json();
}

/**
 * Sort object keys recursively. The CDN serves whatever key order FastAPI
 * produced; without this a re-serialization reorders unrelated keys and the
 * snapshot diff stops being readable.
 */
function sortDeep(value) {
  if (Array.isArray(value)) {
    return value.map(sortDeep);
  }
  if (value !== null && typeof value === "object") {
    return Object.fromEntries(
      Object.keys(value)
        .sort()
        .map((key) => [key, sortDeep(value[key])]),
    );
  }
  return value;
}

/** operationId -> { method, path }, in operationId order. */
function operationTable(document) {
  const operations = [];
  for (const [route, item] of Object.entries(document.paths)) {
    for (const [method, operation] of Object.entries(item)) {
      if (!operation?.operationId) continue;
      operations.push({
        operationId: operation.operationId,
        method: method.toUpperCase(),
        path: route,
      });
    }
  }
  operations.sort((a, b) => a.operationId.localeCompare(b.operationId));
  return operations;
}

function writeTypeScriptOperations(document, operations) {
  const entries = operations
    .map(
      (operation) =>
        `  ${operation.operationId}: { method: "${operation.method}", path: "${operation.path}" },`,
    )
    .join("\n");

  writeFileSync(
    path.join(tsGenerated, "operations.ts"),
    `${BANNER}

/** \`info.version\` of the contract these artifacts were generated from. */
export const CONTRACT_VERSION = "${document.info.version}";

/** Every operation the published contract defines, by \`operationId\`. */
export const PUBLISHED_OPERATIONS = {
${entries}
} as const;

export type PublishedOperationId = keyof typeof PUBLISHED_OPERATIONS;
`,
  );
}

function writePythonOperations(document, operations) {
  const entries = operations
    .map(
      (operation) =>
        `    "${operation.operationId}": Operation(method="${operation.method}", path="${operation.path}"),`,
    )
    .join("\n");

  writeFileSync(
    path.join(pyGenerated, "operations.py"),
    `${PY_BANNER}

from __future__ import annotations

from typing import NamedTuple

#: \`\`info.version\`\` of the contract these artifacts were generated from.
CONTRACT_VERSION = "${document.info.version}"


class Operation(NamedTuple):
    """One published operation: its HTTP method and its \`\`/v1\`\`-relative path."""

    method: str
    path: str


#: Every operation the published contract defines, by \`\`operationId\`\`.
PUBLISHED_OPERATIONS: dict[str, Operation] = {
${entries}
}
`,
  );
}

async function main() {
  const document = await fetchContract();
  const operations = operationTable(document);

  mkdirSync(path.dirname(contractPath), { recursive: true });
  mkdirSync(tsGenerated, { recursive: true });
  mkdirSync(pyGenerated, { recursive: true });

  writeFileSync(contractPath, `${JSON.stringify(sortDeep(document), null, 2)}\n`);
  console.log(
    `wrote ${path.relative(root, contractPath)} ` +
      `(${String(Object.keys(document.paths).length)} paths, ` +
      `${String(operations.length)} operations, v${document.info.version})`,
  );

  writeTypeScriptOperations(document, operations);
  writePythonOperations(document, operations);

  console.log(`running ${OPENAPI_TYPESCRIPT}`);
  const types = run("npx", ["--yes", OPENAPI_TYPESCRIPT, contractPath, "--root-types"]);
  writeFileSync(path.join(tsGenerated, "types.ts"), `${BANNER}\n\n${types.trim()}\n`);

  console.log(`running ${DATAMODEL_CODE_GENERATOR}`);
  run("uvx", [
    "--from",
    DATAMODEL_CODE_GENERATOR,
    "datamodel-codegen",
    "--input",
    contractPath,
    "--input-file-type",
    "openapi",
    "--output-model-type",
    "pydantic_v2.BaseModel",
    "--target-python-version",
    "3.11",
    "--use-standard-collections",
    "--use-union-operator",
    "--disable-timestamp",
    "--formatters",
    "ruff-format",
    "--output",
    path.join(pyGenerated, "models.py"),
  ]);

  writeFileSync(
    path.join(pyGenerated, "__init__.py"),
    `${PY_BANNER}

from octogen_ai_sdk.generated.operations import (
    CONTRACT_VERSION,
    PUBLISHED_OPERATIONS,
    Operation,
)

__all__ = ["CONTRACT_VERSION", "PUBLISHED_OPERATIONS", "Operation"]
`,
  );

  // The generators do not know about this repo's formatting.
  run("npx", ["prettier", "--write", "--ignore-path", "/dev/null", tsGenerated], {
    stdio: ["ignore", "ignore", "inherit"],
  });
  run("uv", [
    "run",
    "--project",
    "sdks/python",
    "ruff",
    "format",
    "--config",
    "sdks/python/pyproject.toml",
    pyGenerated,
  ]);

  console.log("codegen complete");
}

await main();
